swagger: "2.0"
info:
  title: JWT API
  x-ibm-name: jwt-api
  version: 1.0.0
schemes:
- https
basePath: /jwt
security:
- {}
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - switch:
        version: 2.0.0
        title: switch
        case:
        - condition: (($httpVerb() = 'GET' and $operationPath() = '/gen'))
          execute:
          - set-variable:
              version: 2.0.0
              title: set-variable
              actions:
              - set: hs256-key
                value: '{ "alg": "HS256", "kty": "oct", "use": "sig", "k": "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
                  "kid": "hs256-key" }'
                type: string
          - jwt-generate:
              version: 2.0.0
              title: jwt-generate
              jwt: generated.jwt
              iss-claim: request.headers.iss-claim
              exp-claim: 3600
              aud-claim: request.headers.aud-claim
              jws-jwk: hs256-key
              jws-alg: HS256
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: |-
                var apim = require('apim');
                apim.setvariable('message.body',apim.getvariable('generated.jwt'));
        - condition: (($httpVerb() = 'GET' and $operationPath() = '/val'))
          execute:
          - set-variable:
              version: 2.0.0
              title: set-variable
              actions:
              - set: hs256-key
                value: '{ "alg": "HS256", "kty": "oct", "use": "sig", "k": "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
                  "kid": "hs256-key" }'
                type: string
          - jwt-validate:
              version: 2.0.0
              title: jwt-validate
              jwt: request.headers.authorization
              output-claims: decoded.claims
              jwe-jwk: ""
              jws-jwk: hs256-key
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: |-
                var apim = require('apim');
                apim.setvariable('message.body',apim.getvariable('decoded.claims'));
    catch:
    - default:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var apim = require('apim');
            apim.setvariable('message.body',apim.getvariable('jwt-validate.error-message'))
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
paths:
  /val:
    parameters: []
    get:
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Enter Bearer <jwt>
        type: string
      produces:
      - application/json
      consumes: []
  /gen:
    get:
      responses:
        "200":
          description: 200 OK
          schema:
            type: string
      parameters:
      - name: iss-claim
        in: header
        required: true
        description: https://myidp.ibm.com
        type: string
      - name: aud-claim
        in: header
        required: true
        description: Enter ClientID1
        type: string
